FROM python:3.12-alpine

LABEL AUTHORS="Cactus Maestro (c) https://github.com/qerdinger/cactus-maestro - MIT License"
LABEL IMG_LICENSE="MIT"
LABEL VERSION="1.0.0"

ENV CACTUIZED="true"
ENV BUILD_ON="Cactus Maestro"
ENV INTERPRETER="python3.12"

ENTRYPOINT [ "python3.12" ]